
 
### 유저 GET
GET 127.0.0.1:3000
Content-Type: application/json

### 유저 SIGUP
POST localhost:3000/users/signup
Content-Type: application/json

{
  "name": "성민섭",
  "email": "ms_sh0728@naver.com",
  "emailConfirm": "1520",
  "password": "1234",
  "passwordConfirm": "1234",
  "phone": "01012341234"
}

### 유저 LOGIN
# @no-cookie-jar
POST localhost:3000/users/login
Content-Type: application/json

{
  "email": "ms_sh0728@naver.com",
  "password":"1234"
}

### 유저 LOOUT
GET localhost:3000/users/logout
Content-Type: application/json


### test
POST localhost:3000/users/sendMail
Content-Type: application/json

{
  "name": "테스트입니당",
  "email": "ms_sh0728@naver.com"
}

### 상품
GET localhost:3000/admin/userInfo
Content-Type: application/json


### 상품
GET localhost:3000/products/list
Content-Type: application/json


### 유저 삭제
POST localhost:3000/admin/users/2
Content-Type: application/json

### 상품등록
POST localhost:3000/admin/product
Content-Type: multipart/form-data

### 상품 목록
GET localhost:3000/admin/userOrder
Content-Type: application/json