GET localhost:3000/admin/users/1
Content-Type: application/json

{
  "userid": 1
}

### 유저 SIGUP
POST localhost:3000/users/signup
Content-Type: application/json

{
"name": "1",
"email":"jinro@jinro.com",
"password": "1234",
"phone": "01012341234"
}

### 유저 LOGIN
# @no-cookie-jar
POST localhost:3000/users/login
Content-Type: application/json

{
  "email": "jinro@jinro.com",
  "password":"1234"
}

### 유저 LOOUT
GET localhost:3000/users/logout
Content-Type: application/json